/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./components/AppLink.vue')['default']
    BlackCard: typeof import('./components/BlackCard.vue')['default']
    BlueButton: typeof import('./components/BlueButton.vue')['default']
    ContactForm: typeof import('./components/ContactForm.vue')['default']
    HousePackage: typeof import('./components/HousePackage.vue')['default']
    HouseProduct: typeof import('./components/HouseProduct.vue')['default']
    IndustryStoreProduct: typeof import('./components/IndustryStoreProduct.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollCard: typeof import('./components/ScrollCard.vue')['default']
    ScrollCardView: typeof import('./components/ScrollCardView.vue')['default']
    ScrollFrame: typeof import('./components/ScrollFrame.vue')['default']
    SplitTitle: typeof import('./components/SplitTitle.vue')['default']
    TabButtonGroup: typeof import('./components/TabButtonGroup.vue')['default']
    TheAlignContainer: typeof import('./components/TheAlignContainer.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
